### ISSUE TITLE
MIP

### ISSUE THREAD

**Issue by sandrinegagne** [pmc-rosie/rosie_ros#23]

**Comment by sandrinegagne** [comment]
RÉFÉRENCE : LH
Intrant : LH
Analyse de risque : AG
Bras robotique : PM
Station de recharge : PM
Photos d'architecture + plate-forme mobile : CB
Estimation temps : LH
Stratégie de gestion : AG
Conclusion : SG
Annexe n'apparait pas à la table des matières : PM
Détailler importance pour chq requis: PM

**Comment by AliceGarceau814** [comment]
C'est complété pour moi (analyse de risque + stratégie de gestion)
