### ISSUE TITLE
Diagramme de séquence du système d'identification V0

### ISSUE THREAD

**Issue by emarcoux23** [pmc-rosie/rosie_ros#38]

**Comment by AliceGarceau814** [comment]
J'ai fait une première version, dans le logbook général sur le drive

**Comment by CharloLeRigolo** [comment]
Première ébauche révisé à 3.
https://drive.google.com/file/d/14UPSI4cS3Urq3cZNqUmxjFu16wE9LtBK/view?usp=sharing
