### ISSUE TITLE
Étude de marché des capteurs RFID

### ISSUE THREAD

**Issue by emarcoux23** [pmc-rosie/rosie_ros#8]

**Comment by sandrinegagne** [comment]
Durant la visite chez C8, j'ai effectué un test avec mon cellulaire et une pastille RFID. Lorsque les 2 étaient collé de chaque côté d'une porte de cabinet, rien ne fonctionnait, et ce, malgré les trous dans la porte. 

Également, j'ai entendu dire par d'autres que Ryan trouve la solution dispendieuse (d'ajouter des RFID sur chaque unités)
